INPUT:
  SIZE: (224, 224)
  TRANSFORMS: ['random_flip', 'random_translation', 'colorjitter', 'normalize']

DATASET:
  NAME: 'OfficeHomeDG'

MODEL:
  BACKBONE:
    NAME: 'resnet50_dynamic_ms_l12'
    PRETRAINED: True
