INPUT:
  SIZE: (224, 224)
  TRANSFORMS: ['random_flip', 'random_translation', 'colorjitter', 'randomgrayscale', 'gaussian_blur', 'normalize']

DATASET:
  NAME: 'PACS'

MODEL:
  BACKBONE:
    NAME: 'resnet50_dynamic'
    PRETRAINED: True
